from .Programs.error_source import error_details,read_errors,update_errorslog
from .OOPS.Student_Records_System.Domain.student_registration import StudentMenu,Student
from .OOPS.Student_Records_System.Report.search_student import StudentSearch
from .OOPS.Student_Records_System.Utils.read_writedata import DataOperations